nickrobison-usds/demand-modeler

ui/src/components/EpiMap.tsx

Zooms to state and counties on map click

Add state and county click handler

---

README.md
api/counties.go
api/router.go
api/states.go
cmd/types.go

Added corresponding `/state` endpoint which returns matching data from `/county` endpoints, only updated to include reported time as well.

Add State API endpoint

---

ui/src/components/Charts/StateMixedBar.tsx

Shows all X labels for Top 10 charts

Show all X labels, use angle

---

README.md

Was 404ing downloading the county file. Took a guess at the right URL; this seemed to work

Fix COUNTY readme typo

---

ui/src/app/mockData.ts
ui/src/components/Charts/StateMixedBar.tsx
ui/src/stories/Test.stories.tsx
ui/tsconfig.json

`StateMixedBar` component switched over to new state structure

Update bar chart data model

---

ui/src/components/Charts/StateMixedBar.tsx

uses `formatDate` on bar chart

Bar chart dates

---

ui/src/components/Charts/MixedBar.tsx
ui/src/stories/Test.stories.tsx

Mixed chart data structure fixed

Fix MixedChart for new structure

---

ui/src/App.tsx
ui/src/components/Charts/ChartContainer.tsx
ui/src/components/Charts/Report.tsx
ui/src/components/Charts/StateMixedBar.tsx
ui/src/stories/Test.stories.tsx

Fixes report for new data structure

Fix report and cleanup charts

---

ui/src/components/Charts/MixedBar.tsx
ui/src/components/Charts/Report.tsx
ui/src/components/Charts/StateMixedBar.tsx

Adds a prop to the chart components so it'll look good in report view or on web app

Add report view prop

---

ui/src/components/Forms/CountySelect.tsx
ui/src/components/Forms/StateSelect.tsx

- Filter county dropdown to only show ones in the correct state
- Clear county selection if state changes

Fix county selection and clear it when switching states

---

ui/src/App.tsx
ui/src/api.ts
ui/src/app/AppStore.tsx
ui/src/components/ApiContainer.tsx
ui/src/utils/guards.ts

Integrates the app with the api!

API integration

---

.circleci/config.yml
.dockerignore
Dockerfile

Update React URL to point to the relative base.
Remove CircleCI deploy job.
Exclude big files from Docker image.

Hotfix REACT url

---

api/counties.go
api/states.go
ui/src/api.ts
ui/src/components/ApiContainer.tsx

Added root routes to the `/state` and `/county` to return the top _x_ counties and states based on the latest reports.
Updated the UI to use these new endpoints for the initial data loading.

Add aggregate API endpoints

---

ui/src/app/mockData.ts
ui/src/components/Charts/MixedBar.tsx

- Fixes grand total charts at state level
- Fixes mock data (runtime error trying to push to nonexistent arrays)
- Autoformatting because format-on-save rules

Fix state-level grand totals and mock data

---

ui/src/components/Charts/Report.tsx

Makes "Last Updated" datetime dynamic for the Report.

Add dynamic last updated date to report

---

ui/src/App.tsx
ui/src/components/USATotals.tsx
ui/src/stories/Test.stories.tsx
ui/src/utils/DateUtils.ts

- Fixes USATotals
- Still not uncommented from the App code

Fix USA Totals component and add storyshots

---

ui/src/app/mockState.ts
ui/src/utils/__test__/calculations.test.ts
ui/src/utils/__test__/matchers.ts
ui/src/utils/calculations.ts

- Creates `calculations.ts` file that does some of the important chart-related calcuations
- _Does not_ integrate these calculations into components yet
**Importantly** these calculations don't handle any duplicate remove. I still think we should do that when loading data

Isolate math functions

---

ui/src/App.tsx
ui/src/components/Maps/CountyMap.tsx

- Resize map to fit container (and resize on window resize)
- Rename "New" to "Percent Increase" and fix that calculation

Add map resize and Percent Increase

---

ui/src/components/Charts/MixedBar.tsx
ui/src/components/Charts/StateBar.tsx
ui/src/components/Charts/StateMixedBar.tsx
ui/src/components/Maps/CountyMap.tsx
ui/src/pages/Dashboard.tsx
ui/src/utils/useResizeToContainer.ts

- Custom resize hook 🎉 
- Resize charts to container width if a `chartWidth` prop is passed (so no effect on the Report view)

Resize charts

---

ui/src/components/Maps/CountyMap.tsx

Adds better state-level geojson file

Add better state geo

---

ui/src/components/Charts/CountyTrendGraph.tsx
ui/src/components/Maps/CountyMap.css
ui/src/components/Maps/CountyMap.tsx

Adds tooltip with state/county names and selected metric count

Add tooltip labels to map

---

ui/package.json
ui/src/components/Maps/CountyMap.tsx
ui/src/components/USATotals.tsx
ui/yarn.lock

-Zooms to a state on selection
-Select counties and states by clicking on map
-Selections are tied to app-wide selections

Zoom to state on selection

---

ui/src/components/Maps/CountyMap.tsx

- Alaska didn't zoom correctly. Not sure why, so I created custom zoom lat/long coords

Custom coords for Alaska zoom bug

---

ui/src/components/Forms/CountySelect.tsx
ui/src/components/Forms/StateSelect.tsx

- Orders states and counties and alphabetical order in the dropdowns

Order states and counties alphabetically

---

ui/src/components/Charts/CountyTrendGraph.tsx
ui/src/pages/Dashboard.tsx

- Filters the line graph if a state is selected
- Hides the line graph if a county is selected

Filter line graph on state select

---

ui/src/app/AppStore.tsx
ui/src/components/Charts/MixedBar.tsx
ui/src/components/Charts/PieChartBreakdown.tsx
ui/src/components/Charts/RenderChart.tsx
ui/src/components/Charts/StateBar.tsx
ui/src/components/Charts/StateMixedBar.tsx
ui/src/components/Charts/Top10Counties.tsx
ui/src/components/Maps/CountyMap.tsx
ui/src/pages/Dashboard.tsx

- Map side-by-side with some charts

Alternative dashboard layout

---

ui/src/components/Card/Card.tsx
ui/src/components/Charts/CountyTrendGraph.tsx
ui/src/components/Charts/MixedBar.tsx
ui/src/components/Charts/RenderChart.tsx
ui/src/components/Maps/CountyMap.tsx
ui/src/pages/Dashboard.scss
ui/src/pages/Dashboard.tsx
ui/src/pages/Report.tsx
ui/src/utils/utils.ts

- Makes charts more legible
- Responsive layout
- Fix some small bugs

Responsive dashboard

---

ui/src/components/Charts/CountyTrendGraph.tsx

- Limit to top 20 counties
- Better colors
- Custom legend

Clean up line graph

---

ui/src/components/Charts/CountyTrendGraph.tsx

Adds numbering to county labels for clarity on ordering

Add numbering to legend for clarity

---

ui/src/components/Charts/MixedBar.tsx

Adds "New" cases to existing stacked bar

Add New cases to MixedBar

---

ui/src/components/Charts/MixedBar.tsx

- Flips new and existing cases in chart

Flip New and Existing

---

ui/src/app/AppStore.tsx
ui/src/app/mockState.ts
ui/src/components/Forms/MetricSelect.tsx
ui/src/components/Maps/CountyMap.tsx
ui/src/pages/Dashboard.tsx
ui/src/stories/Test.stories.tsx

- Adds mortality selection to overall state
- Filters the map (and only the map!) to see mortality stats
- Mortality stats for other components in the works

Add mortality

---

ui/src/components/Charts/MixedBar.tsx
ui/src/components/Charts/StateBar.tsx
ui/src/components/Charts/StateMixedBar.tsx
ui/src/components/Charts/StripedFill.tsx
ui/src/components/Charts/Top10Counties.tsx

- Adds "New" cases in stacked bar graphs

Stacked mixed bars initial attempt

---

ui/src/components/Charts/MixedBar.tsx
ui/src/components/Charts/StateBar.tsx

- Remove "Existing Cases" from legends

Simplify legends

---

ui/src/components/Charts/StateBar.tsx
ui/src/components/Charts/StateMixedBar.tsx
ui/src/components/Charts/Top10Counties.tsx

This reverts commit d948e8f7c591934d9f72562786d92a01d0a3564c.

Revert "Stacked mixed bars initial attempt"

---

ui/src/components/Charts/MixedBar.tsx
ui/src/components/Charts/StateBar.tsx
ui/src/components/Charts/StateMixedBar.tsx
ui/src/components/Charts/Top10Counties.tsx

- Reintroduces stacked bar display
- Bug introduced with stacked bars not showing right in expanded dashboard view

Reintro stacked bars

---

ui/src/components/Charts/StripedFill.tsx
ui/src/utils/useUniqueId.ts

- Fixes dashboard striped bar behavior in expended view

Fix bars in expanded dashboard view

---

ui/src/components/Charts/StateBar.tsx
ui/src/pages/Report.tsx

- Adds the ability to do 20+ counties (still can do top 10)

20 plus counties

---

data/sources.md

A table of source links and what data they have.

Adding county-level sources by state

---

ui/src/components/ApiContainer.tsx
ui/src/components/ReportContainer.tsx
ui/src/utils/reportHelpers.ts

- Adds metro area charts!
- Grabs data starting *February 29* so we can accurately calculate new cases

County charts

---

cmd/loader.go
main.go

Attempt to address startup issues in Heroku.
Data loading is async, which should help work around the startup issues in Heroku and cloud.gov.
Also removed some superfluous newline formatting in the log output.

Hotfix application startup failure

---

ui/src/components/PowerPointGenerator/Slides/CBSASlides/CBSAStackedBars.ts
ui/src/components/PowerPointGenerator/Slides/Templates/InteriorSlides/StackedBarChartWithTitle.ts
ui/src/components/ReportContainer.tsx

- Adds multi-CBSA slides
- Titles not included

Adds multislides
